### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liang-android** [mustime/Adrill#2]
3|aosp:/data/local/tmp # ./i  --pid 11529 --libpath /data/local/tmp/libudp.so
WARNING: linker: /data/local/tmp/i: unsupported flags DT_FLAGS_1=0x8000001
[!] func 'mmap'(0xc75a88b0) is not within module '/system/lib/libc.so'(0xffffffff-0x0)
[!] func 'munmap'(0xc75f75c4) is not within module '/system/lib/libc.so'(0xffffffff-0x0)
[!] func 'dlopen'(0xc771834c) is not within module '/system/lib/libdl.so'(0xffffffff-0x0)
[!] func 'dlerror'(0xc7718200) is not within module '/system/lib/libdl.so'(0xffffffff-0x0)
[!] something went wrong, see errors listed above.

**Comment by liang-android** [comment]
在模拟器上注入

**Comment by mustime** [comment]
具体是什么模拟器呢？系统版本多少
