### ISSUE TITLE
dlopen failed: library

### ISSUE THREAD

**Issue by sssmem** [mustime/Adrill#3]
Hello, I made the following error when using your tool.It may be the problem of SO. Could you please provide the case of so injection? Thank you  
![error](https://user-images.githubusercontent.com/68261842/138409323-5068188c-7fd2-4a39-bd1b-68ee9a72019c.png)

**Comment by mustime** [comment]
Could you please try rebuilding `libceshi.so` with simply one file:

```cpp
// test.cpp
#include <android/log.h>

void __attribute__((constructor)) test() {
    __android_log_print(ANDROID_LOG_DEBUG, "test", ">>> enter test");
}
```

And see if `dlopen` works?

**Comment by sssmem** [comment]
> 您能否尝试`libceshi.so`仅使用一个文件进行重建：
> 
> ```c++
> // TEST.CPP 
> ＃包括 <机器人/ log.h >
> 
> 空隙 __attribute__（（构造））测试（）{
>      __android_log_print（ANDROID_LOG_DEBUG， “测试”， “ >>>进入测试”）; 
> }
> ```
> 
> 看看是否`dlopen`有效？

I just tried using the demo you sent and still reported the same error.

**Comment by mustime** [comment]
It looks like the `--libpath` specified library path is not accessible with the current user. (restriction since Android N)
If you're running Adrill from user App, try replacing it with data dir like  `/data/data/<app_package>/files`.

**Comment by ATCThunder** [comment]
我也是这个问题，我将注入工具adril和so,都一起放在了目标app的files中，还是出现了这个问题
