### ISSUE TITLE
dlopen问题

### ISSUE THREAD

**Issue by ATCThunder** [mustime/Adrill#6]
按照你的方法，将so文件放到目标app的files文件夹中，依然还是不能正常注入

**Comment by mustime** [comment]
不进一步提供有效信息没有办法帮助你。例如具体执行的命令，以及对应命令的输出？

**Comment by ATCThunder** [comment]
和#2一模一样的问题，我已经通过其他手段注入成功了，非常感谢您

**Comment by ATCThunder** [comment]
最近正在学习如何隐藏注入的so，大佬有什么好的建议吗？

**Comment by mustime** [comment]
> 最近正在学习如何隐藏注入的so，大佬有什么好的建议吗？

一般来说，本质上都是通过 `mmap` 重新映射 so 的内存区域，但是传入的 fd 为 -1 即可。

**Comment by mustime** [comment]
> 最近正在学习如何隐藏注入的so，大佬有什么好的建议吗？

找到了个参考：https://github.com/RikkaApps/Riru/blob/master/riru/src/main/cpp/hide/hide.cpp

**Comment by ATCThunder** [comment]
嗯，我之前尝试学习过这个

**Comment by ATCThunder** [comment]
我尝试调用riru_hide方法，但是出现了一些未知问题

**Comment by ATCThunder** [comment]
可能是其对ptrace函数的检测，有不使用ptrace方法进行注入的好方法吗？

**Comment by ATCThunder** [comment]
参考过
https://github.com/AonCyberLabs/Cexigua
但完全看不懂

**Comment by ATCThunder** [comment]
> > 最近正在学习的小伙子提出了好的建议，大佬如何隐藏有什么好的建议？
> 
> 找到了个参考：https://github.com/RikkaApps/Riru/blob/master/riru/src/main/cpp/hide/hide.cpp

非常感谢

**Comment by mustime** [comment]
> 可能是其对ptrace函数的检测，有不使用ptrace方法进行注入的好方法吗？

第三方进程注入只有这个办法；否则就是用类似 VirtualApp 之类的沙盒注入（进程关系变成可管理的子进程）。

**Comment by ATCThunder** [comment]
> > 可能是其对 ptrace 函数的检测，有没有使用 ptrace 方法进行注入的好方法吗？
> 
> 就是这个进程唯一植入这个进程；否则类似VirtualApp之类的用沙盒插入办法（进程关系变成可以管理的子进程）。

好的，谢谢你的回复
